import React from 'react';
import { WineData } from '../types';
import { Download, MapPin, Award, Droplet, Info, TrendingUp, Calendar, Utensils, Thermometer, Box, Wine as WineIcon, Mountain, Leaf, Warehouse, Star, ExternalLink, Lightbulb, Clock, BookOpen } from 'lucide-react';
import { VintageChart } from './VintageChart';

interface WineDisplayProps {
  data: WineData;
  imagePreview: string | null;
}

export const WineDisplay: React.FC<WineDisplayProps> = ({ data, imagePreview }) => {
  
  // Logic: Prefer User Scan -> Then Online Image Found by AI -> Then Fallback
  const displayImage = imagePreview || data.onlineImage || 'https://images.unsplash.com/photo-1559563362-c667ba5f5480?auto=format&fit=crop&q=80&w=600';
  
  // Logic: Determine if we have a valid link to wrap the image
  const WebsiteWrapper = ({ children }: { children: React.ReactNode }) => {
    if (data.websiteUrl) {
      return (
        <a 
          href={data.websiteUrl} 
          target="_blank" 
          rel="noopener noreferrer" 
          className="group relative block cursor-pointer"
        >
          {children}
          <div className="absolute inset-0 bg-black/0 group-hover:bg-black/10 transition-colors flex items-center justify-center opacity-0 group-hover:opacity-100">
             <div className="bg-white/90 px-4 py-2 rounded-full shadow-lg flex items-center gap-2 transform translate-y-2 group-hover:translate-y-0 transition-all">
                <span className="text-xs font-bold text-wine-900 uppercase">Visit Winery</span>
                <ExternalLink className="w-3 h-3 text-wine-900" />
             </div>
          </div>
        </a>
      );
    }
    return <div className="relative">{children}</div>;
  };

  const downloadInfo = () => {
    const content = `
WINE REPORT: ${data.name}
================================
Generated by Sommelier AI

DETAILS
-------
Vintage: ${data.vintage}
Type: ${data.type}
Country: ${data.country}
Region: ${data.region}
Sub-Region: ${data.subRegion || 'N/A'}
Varietals: ${data.varietals.join(', ')}
ABV: ${data.abv}

CRITIC SCORES
-------------
${data.criticScores?.map(c => `${c.critic}: ${c.score}`).join('\n') || 'N/A'}

TERROIR & WINEMAKING
--------------------
Soil: ${data.terroir?.soil.join(', ') || 'N/A'}
Oak: ${data.terroir?.oak || 'N/A'}
Farming: ${data.terroir?.farming.join(', ') || 'N/A'}

STYLE PROFILE
-------------
Body: ${data.styleProfile?.body || 'N/A'}
Acidity: ${data.styleProfile?.acidity || 'N/A'}
Tannins: ${data.styleProfile?.tannins || 'N/A'}

TASTING NOTES
-------------
Color: ${data.color}
Nose: ${data.nose}
Taste: ${data.taste}

AGING & INVESTMENT
------------------
Drink Window: ${data.aging?.drinkFrom} - ${data.aging?.drinkUntil}
Peak Years: ${data.aging?.peakYears}
Investment Grade: ${data.aging?.investmentPotential}
Est. Value (5yr): ${data.aging?.estimatedValue5Years}

PAIRING & SERVICE
-----------------
Temp: ${data.pairing?.temperature}
Glassware: ${data.pairing?.glassware}
Decanting: ${data.pairing?.decanting}
Foods: ${data.pairing?.foods.join(', ')}

MARKET
------
Current Price: ${data.marketPrice}

HERITAGE & HISTORY
------------------
Origins: ${data.wineryInfo}
Best Vintages: ${data.bestVintages?.join(', ') || 'N/A'}

DID YOU KNOW?
-------------
${data.funFacts?.join('\n- ') || 'N/A'}

Website: ${data.websiteUrl || 'N/A'}

SOURCES
-------
${data.sources?.join('\n') || 'Gemini Knowledge Base'}
    `.trim();

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${data.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_Report.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="bg-white rounded-[2rem] shadow-xl overflow-hidden mb-32 mx-4 border border-wine-100/50">
      {/* Hero Image Section */}
      <div className="relative h-72 bg-gradient-to-b from-wine-50/50 to-white">
        <WebsiteWrapper>
            <img 
              src={displayImage} 
              alt="Wine Label" 
              className="w-full h-full object-contain p-6 mix-blend-multiply drop-shadow-xl transition-transform duration-500 hover:scale-105"
            />
        </WebsiteWrapper>
        
        <div className="absolute top-4 right-4 bg-white/90 backdrop-blur-md px-4 py-1.5 rounded-full text-wine-900 font-serif font-bold shadow-sm border border-wine-100">
          {data.vintage}
        </div>
      </div>

      {/* Main Content */}
      <div className="p-8 space-y-10">
        
        {/* Title Block */}
        <div className="text-center border-b border-wine-100 pb-8">
          <h2 className="text-3xl font-serif font-bold text-wine-950 leading-tight tracking-tight">{data.name}</h2>
          <div className="flex items-center justify-center gap-2 mt-3 text-wine-700 font-medium text-sm tracking-wide uppercase opacity-80 mb-4">
            <MapPin className="w-4 h-4" />
            <span>{data.region}, {data.country}</span>
          </div>

          {/* Critic Scores Badge Row */}
          {data.criticScores && data.criticScores.length > 0 && (
            <div className="flex flex-wrap items-center justify-center gap-2 animate-fade-in">
              {data.criticScores.map((c, i) => (
                <div key={i} className="bg-wine-900 text-wine-50 px-3 py-1 rounded-full text-xs font-bold shadow-sm flex items-center gap-1.5 border border-wine-800">
                   <Star className="w-3 h-3 text-gold-400 fill-gold-400" />
                   <span className="opacity-90">{c.critic}</span>
                   <span className="bg-white/20 px-1.5 rounded text-white">{c.score}</span>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Identity & Origin Grid */}
        <div>
           <h3 className="text-xs font-bold text-wine-400 uppercase tracking-widest mb-4">Identity & Origin</h3>
           <div className="grid grid-cols-2 gap-4">
            <div className="bg-wine-50/80 p-4 rounded-2xl border border-wine-100/50">
              <p className="text-[0.65rem] text-wine-400 uppercase tracking-wider font-bold mb-1">Grapes</p>
              <div className="flex flex-wrap gap-1">
                 {data.varietals.map((v, i) => (
                    <span key={i} className="text-xs font-semibold text-wine-900 bg-white/50 px-1.5 py-0.5 rounded-md">{v}</span>
                 ))}
              </div>
            </div>
            <div className="bg-wine-50/80 p-4 rounded-2xl border border-wine-100/50">
              <p className="text-[0.65rem] text-wine-400 uppercase tracking-wider font-bold mb-1">Alcohol</p>
              <p className="font-semibold text-wine-900">{data.abv}</p>
            </div>
            {data.styleProfile && (
                <>
                <div className="bg-wine-50/80 p-4 rounded-2xl border border-wine-100/50">
                  <p className="text-[0.65rem] text-wine-400 uppercase tracking-wider font-bold mb-1">Body</p>
                  <p className="font-semibold text-wine-900">{data.styleProfile.body}</p>
                </div>
                 <div className="bg-wine-50/80 p-4 rounded-2xl border border-wine-100/50">
                  <p className="text-[0.65rem] text-wine-400 uppercase tracking-wider font-bold mb-1">Structure</p>
                  <p className="text-xs font-semibold text-wine-900">
                    Tannins: {data.styleProfile.tannins}
                  </p>
                </div>
                </>
            )}
           </div>
        </div>

        {/* Terroir & Winemaking */}
        {data.terroir && (
          <div>
            <h3 className="flex items-center gap-2 text-lg font-serif font-bold text-wine-950 mb-4">
              <Mountain className="w-5 h-5 text-wine-500" /> Terroir & Method
            </h3>
            <div className="bg-stone-50 border border-stone-200 rounded-2xl p-5 space-y-4">
               {data.terroir.soil && data.terroir.soil.length > 0 && (
                 <div className="flex items-start gap-3">
                    <div className="bg-white p-2 rounded-full shadow-sm text-stone-600">
                      <Mountain className="w-4 h-4" />
                    </div>
                    <div>
                      <p className="text-xs font-bold text-stone-500 uppercase">Soil Composition</p>
                      <p className="text-stone-800 text-sm font-medium">{data.terroir.soil.join(', ')}</p>
                    </div>
                 </div>
               )}
               {data.terroir.oak && (
                 <div className="flex items-start gap-3">
                    <div className="bg-white p-2 rounded-full shadow-sm text-stone-600">
                      <Warehouse className="w-4 h-4" />
                    </div>
                    <div>
                      <p className="text-xs font-bold text-stone-500 uppercase">Aging & Oak</p>
                      <p className="text-stone-800 text-sm font-medium leading-snug">{data.terroir.oak}</p>
                    </div>
                 </div>
               )}
               {data.terroir.farming && data.terroir.farming.length > 0 && (
                 <div className="flex items-start gap-3">
                    <div className="bg-white p-2 rounded-full shadow-sm text-stone-600">
                      <Leaf className="w-4 h-4" />
                    </div>
                    <div>
                      <p className="text-xs font-bold text-stone-500 uppercase">Farming</p>
                      <div className="flex flex-wrap gap-2 mt-1">
                        {data.terroir.farming.map((f, i) => (
                          <span key={i} className="text-xs bg-green-100 text-green-800 px-2 py-0.5 rounded-full border border-green-200">
                            {f}
                          </span>
                        ))}
                      </div>
                    </div>
                 </div>
               )}
            </div>
          </div>
        )}

        {/* Vintage Analysis (Chart) */}
        {data.vintageComparison && data.vintageComparison.length > 0 && (
          <div>
             <h3 className="flex items-center gap-2 text-lg font-serif font-bold text-wine-950 mb-4">
                <TrendingUp className="w-5 h-5 text-wine-500" /> Vintage Quality
             </h3>
             <div className="bg-white border border-wine-100 rounded-2xl p-4 shadow-sm">
                <VintageChart data={data.vintageComparison} currentVintage={data.vintage} />
             </div>
          </div>
        )}

        {/* Tasting Notes */}
        <div>
          <h3 className="flex items-center gap-2 text-lg font-serif font-bold text-wine-950 mb-4">
            <Droplet className="w-5 h-5 text-wine-500" /> Tasting Profile
          </h3>
          <div className="space-y-4 text-sm text-gray-600 leading-relaxed bg-wine-50/30 p-4 rounded-2xl border border-wine-100/50">
            <div className="flex gap-3">
               <span className="font-bold text-wine-800 w-16 shrink-0 uppercase text-xs tracking-wide pt-1">Eye</span>
               <span>{data.color}</span>
            </div>
            <div className="flex gap-3">
               <span className="font-bold text-wine-800 w-16 shrink-0 uppercase text-xs tracking-wide pt-1">Nose</span>
               <span>{data.nose}</span>
            </div>
            <div className="flex gap-3">
               <span className="font-bold text-wine-800 w-16 shrink-0 uppercase text-xs tracking-wide pt-1">Palate</span>
               <span>{data.taste}</span>
            </div>
          </div>
        </div>

        {/* Cellaring & Investment */}
        {data.aging && (
            <div className="bg-gradient-to-br from-gray-900 to-wine-950 text-wine-50 rounded-2xl p-6 shadow-lg relative overflow-hidden">
                <div className="absolute top-0 right-0 w-32 h-32 bg-wine-800 rounded-full blur-3xl opacity-20 translate-x-10 -translate-y-10"></div>
                <h3 className="flex items-center gap-2 text-lg font-serif font-bold text-gold-400 mb-4 relative z-10">
                    <Box className="w-5 h-5" /> Cellar & Investment
                </h3>
                <div className="grid grid-cols-2 gap-y-6 gap-x-4 relative z-10">
                    <div>
                        <p className="text-[0.65rem] text-wine-300 uppercase tracking-widest mb-1">Drink Window</p>
                        <div className="flex items-center gap-2">
                             <Calendar className="w-4 h-4 text-wine-400" />
                             <p className="font-semibold text-sm">{data.aging.drinkFrom} - {data.aging.drinkUntil}</p>
                        </div>
                    </div>
                    <div>
                        <p className="text-[0.65rem] text-wine-300 uppercase tracking-widest mb-1">Peak Years</p>
                        <p className="font-semibold text-sm text-gold-400">{data.aging.peakYears}</p>
                    </div>
                    <div className="col-span-2 border-t border-white/10 pt-4">
                         <div className="flex justify-between items-end">
                            <div>
                                <p className="text-[0.65rem] text-wine-300 uppercase tracking-widest mb-1">Current Price</p>
                                <p className="font-serif text-xl">{data.marketPrice}</p>
                            </div>
                            <div className="text-right">
                                <p className="text-[0.65rem] text-wine-300 uppercase tracking-widest mb-1">Est. Value (5yr)</p>
                                <p className="font-serif text-xl text-green-400">{data.aging.estimatedValue5Years}</p>
                            </div>
                         </div>
                    </div>
                </div>
            </div>
        )}

        {/* Pairing & Service */}
        {data.pairing && (
            <div>
                <h3 className="flex items-center gap-2 text-lg font-serif font-bold text-wine-950 mb-4">
                    <Utensils className="w-5 h-5 text-wine-500" /> Pairing & Service
                </h3>
                <div className="grid grid-cols-1 gap-3">
                    <div className="grid grid-cols-2 gap-3">
                         <div className="bg-white border border-wine-100 p-4 rounded-xl flex items-start gap-3">
                            <Thermometer className="w-5 h-5 text-wine-400 mt-0.5" />
                            <div>
                                <p className="text-xs font-bold text-wine-900 uppercase">Temp</p>
                                <p className="text-sm text-wine-700">{data.pairing.temperature}</p>
                            </div>
                        </div>
                        <div className="bg-white border border-wine-100 p-4 rounded-xl flex items-start gap-3">
                            <WineIcon className="w-5 h-5 text-wine-400 mt-0.5" />
                            <div>
                                <p className="text-xs font-bold text-wine-900 uppercase">Glassware</p>
                                <p className="text-sm text-wine-700 leading-tight">{data.pairing.glassware}</p>
                            </div>
                        </div>
                    </div>
                    
                    {data.pairing.decanting && (
                        <div className="bg-white border border-wine-100 p-3 rounded-xl flex items-center gap-3 px-4">
                             <div className="w-1.5 h-1.5 rounded-full bg-wine-300"></div>
                             <p className="text-sm text-wine-800"><span className="font-bold">Decant:</span> {data.pairing.decanting}</p>
                        </div>
                    )}

                    <div className="bg-white border border-wine-100 p-4 rounded-xl">
                        <p className="text-xs font-bold text-wine-900 uppercase mb-2">Ideal Matches</p>
                        <div className="flex flex-wrap gap-2">
                            {data.pairing.foods.map((food, i) => (
                                <span key={i} className="text-sm bg-wine-50 text-wine-800 px-3 py-1 rounded-full border border-wine-100">
                                    {food}
                                </span>
                            ))}
                        </div>
                    </div>
                </div>
            </div>
        )}

        {/* Heritage & History (Replaces basic Winery Info) */}
        <div className="bg-stone-50 rounded-2xl border border-stone-200/60 overflow-hidden">
           <div className="p-6 relative">
             <div className="absolute top-0 right-0 w-32 h-32 bg-stone-100 rounded-full blur-2xl -translate-y-1/2 translate-x-1/2"></div>
             
             <h3 className="relative flex items-center gap-2 text-lg font-serif font-bold text-stone-800 mb-4">
               <BookOpen className="w-5 h-5 text-stone-500" /> Heritage & History
             </h3>
             
             {/* Origins / History */}
             <div className="relative mb-6">
                <p className="text-sm text-stone-600 leading-relaxed italic font-serif">
                  "{data.wineryInfo}"
                </p>
             </div>

             <div className="relative grid gap-4">
                {/* Best Vintages */}
                {data.bestVintages && data.bestVintages.length > 0 && (
                  <div className="bg-white p-4 rounded-xl border border-stone-200 shadow-sm">
                      <div className="flex items-center gap-2 mb-2">
                        <Clock className="w-4 h-4 text-wine-600" />
                        <h4 className="text-xs font-bold text-stone-500 uppercase tracking-widest">Legendary Years</h4>
                      </div>
                      <div className="flex flex-wrap gap-2">
                        {data.bestVintages.map((year, i) => (
                          <span key={i} className="px-2 py-1 bg-wine-50 text-wine-800 text-xs font-bold rounded-md border border-wine-100">
                            {year}
                          </span>
                        ))}
                      </div>
                  </div>
                )}

                {/* Fun Facts */}
                {data.funFacts && data.funFacts.length > 0 && (
                  <div className="bg-white p-4 rounded-xl border border-stone-200 shadow-sm">
                      <div className="flex items-center gap-2 mb-2">
                        <Lightbulb className="w-4 h-4 text-gold-500 fill-gold-500" />
                        <h4 className="text-xs font-bold text-stone-500 uppercase tracking-widest">Did you know?</h4>
                      </div>
                      <ul className="space-y-2">
                        {data.funFacts.map((fact, i) => (
                          <li key={i} className="text-sm text-stone-700 leading-snug flex items-start gap-2">
                             <span className="text-gold-500 mt-1">•</span> {fact}
                          </li>
                        ))}
                      </ul>
                  </div>
                )}
             </div>
           </div>
        </div>

        {/* Action Area */}
        <button 
          onClick={downloadInfo}
          className="w-full mt-6 bg-wine-950 text-wine-50 py-4 rounded-xl font-semibold flex items-center justify-center gap-2 active:scale-95 transition-all shadow-lg shadow-wine-900/20 hover:bg-wine-900"
        >
          <Download className="w-5 h-5" />
          Download Wine Report
        </button>

      </div>
    </div>
  );
};