import React from 'react';
import { WineData } from '../types';
import { Download, MapPin, DollarSign, Award, Droplet, Info } from 'lucide-react';

interface WineDisplayProps {
  data: WineData;
  imagePreview: string;
}

export const WineDisplay: React.FC<WineDisplayProps> = ({ data, imagePreview }) => {
  
  const downloadInfo = () => {
    const content = `
WINE REPORT: ${data.name}
================================
Generated by Sommelier AI

DETAILS
-------
Vintage: ${data.vintage}
Type: ${data.type}
Country: ${data.country}
Region: ${data.region}
Sub-Region: ${data.subRegion || 'N/A'}
Varietals: ${data.varietals.join(', ')}
ABV: ${data.abv}
Size: ${data.size}
Closure: ${data.closure}

TASTING NOTES
-------------
Color: ${data.color}
Nose: ${data.nose}
Taste: ${data.taste}

MARKET
------
Estimated Price: ${data.marketPrice}

WINERY
------
${data.wineryInfo}

AWARDS & RECOGNITION
--------------------
${data.awards.map(a => `- ${a}`).join('\n')}

DID YOU KNOW?
-------------
${data.funFacts.map(f => `- ${f}`).join('\n')}

SOURCES
-------
${data.sources?.join('\n') || 'Gemini Knowledge Base'}
    `.trim();

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${data.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_AllAboutWine.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="bg-white rounded-[2rem] shadow-xl overflow-hidden mb-32 mx-4 border border-wine-100/50">
      {/* Hero Image Section */}
      <div className="relative h-72 bg-gradient-to-b from-wine-50/50 to-white">
        <img 
          src={imagePreview} 
          alt="Wine Label" 
          className="w-full h-full object-contain p-6 mix-blend-multiply drop-shadow-xl"
        />
        <div className="absolute top-4 right-4 bg-white/90 backdrop-blur-md px-4 py-1.5 rounded-full text-wine-900 font-serif font-bold shadow-sm border border-wine-100">
          {data.vintage}
        </div>
      </div>

      {/* Main Content */}
      <div className="p-8 space-y-8">
        
        {/* Title Block */}
        <div className="text-center border-b border-wine-100 pb-8">
          <h2 className="text-3xl font-serif font-bold text-wine-950 leading-tight tracking-tight">{data.name}</h2>
          <div className="flex items-center justify-center gap-2 mt-3 text-wine-700 font-medium text-sm tracking-wide uppercase opacity-80">
            <MapPin className="w-4 h-4" />
            <span>{data.region}, {data.country}</span>
          </div>
        </div>

        {/* Quick Stats Grid */}
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-wine-50/80 p-4 rounded-2xl border border-wine-100/50">
            <p className="text-[0.65rem] text-wine-400 uppercase tracking-wider font-bold mb-1">Type</p>
            <p className="font-semibold text-wine-900">{data.type}</p>
          </div>
          <div className="bg-wine-50/80 p-4 rounded-2xl border border-wine-100/50">
            <p className="text-[0.65rem] text-wine-400 uppercase tracking-wider font-bold mb-1">Price Est.</p>
            <div className="flex items-center gap-1 text-wine-900 font-semibold">
              <DollarSign className="w-4 h-4 text-wine-500" />
              {data.marketPrice}
            </div>
          </div>
          <div className="bg-wine-50/80 p-4 rounded-2xl border border-wine-100/50">
            <p className="text-[0.65rem] text-wine-400 uppercase tracking-wider font-bold mb-1">Varietal</p>
            <p className="font-semibold text-wine-900 truncate">{data.varietals[0]}</p>
          </div>
          <div className="bg-wine-50/80 p-4 rounded-2xl border border-wine-100/50">
            <p className="text-[0.65rem] text-wine-400 uppercase tracking-wider font-bold mb-1">ABV</p>
            <p className="font-semibold text-wine-900">{data.abv}</p>
          </div>
        </div>

        {/* Tasting Notes */}
        <div>
          <h3 className="flex items-center gap-2 text-xl font-serif font-bold text-wine-950 mb-4">
            <Droplet className="w-5 h-5 text-wine-500" /> Tasting Profile
          </h3>
          <div className="space-y-4 text-sm text-gray-600 leading-relaxed bg-white p-1 rounded-xl">
            <div className="flex gap-3">
               <span className="font-bold text-wine-800 w-16 shrink-0 uppercase text-xs tracking-wide pt-1">Eye</span>
               <span>{data.color}</span>
            </div>
            <div className="flex gap-3">
               <span className="font-bold text-wine-800 w-16 shrink-0 uppercase text-xs tracking-wide pt-1">Nose</span>
               <span>{data.nose}</span>
            </div>
            <div className="flex gap-3">
               <span className="font-bold text-wine-800 w-16 shrink-0 uppercase text-xs tracking-wide pt-1">Palate</span>
               <span>{data.taste}</span>
            </div>
          </div>
        </div>

        {/* Winery Info */}
        <div className="bg-stone-50 p-6 rounded-2xl border border-stone-200/60 relative overflow-hidden">
           <div className="absolute top-0 right-0 w-24 h-24 bg-stone-100 rounded-full blur-2xl -translate-y-1/2 translate-x-1/2"></div>
           <h3 className="relative flex items-center gap-2 text-xl font-serif font-bold text-stone-800 mb-3">
            <Info className="w-5 h-5 text-stone-500" /> The Winery
          </h3>
          <p className="relative text-sm text-stone-600 leading-relaxed italic font-serif">
            "{data.wineryInfo}"
          </p>
        </div>

        {/* Awards */}
        {data.awards.length > 0 && (
          <div>
            <h3 className="flex items-center gap-2 text-xl font-serif font-bold text-wine-950 mb-4">
              <Award className="w-5 h-5 text-gold-500" /> Accolades
            </h3>
            <ul className="grid grid-cols-1 gap-3">
              {data.awards.map((award, i) => (
                <li key={i} className="flex items-start gap-3 text-sm text-gray-700 bg-wine-50/50 p-3 rounded-xl border border-wine-100/30">
                  <span className="mt-1.5 w-1.5 h-1.5 rounded-full bg-gold-500 shrink-0 shadow-sm"></span>
                  {award}
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Action Area */}
        <button 
          onClick={downloadInfo}
          className="w-full mt-6 bg-wine-950 text-wine-50 py-4 rounded-xl font-semibold flex items-center justify-center gap-2 active:scale-95 transition-all shadow-lg shadow-wine-900/20 hover:bg-wine-900"
        >
          <Download className="w-5 h-5" />
          Download Wine Report
        </button>

      </div>
    </div>
  );
};