import React, { useState } from 'react';
import { WineData } from '../types';
import { Download, MapPin, Droplet, TrendingUp, Calendar, Utensils, Thermometer, Box, Wine as WineIcon, Mountain, Leaf, Warehouse, Star, ExternalLink, Lightbulb, Clock, BookOpen, ChevronDown, ChevronUp, Activity } from 'lucide-react';
import { VintageChart } from './VintageChart';

interface WineDisplayProps {
  data: WineData;
  imagePreview: string | null;
}

// Helper Component: Progress Bar for Style Profile
const StyleMeter = ({ label, value }: { label: string; value: string }) => {
  // Simple heuristic to map text to percentage
  const getPercentage = (val: string) => {
    const v = val.toLowerCase();
    if (v.includes('high') || v.includes('full') || v.includes('intense')) return 95;
    if (v.includes('medium-plus') || v.includes('med+')) return 75;
    if (v.includes('medium') || v.includes('moderate')) return 50;
    if (v.includes('low') || v.includes('light')) return 25;
    if (v.includes('silky') || v.includes('smooth')) return 60; // Contextual mapping
    return 50; // Default
  };

  const pct = getPercentage(value);

  return (
    <div className="mb-3">
      <div className="flex justify-between items-end mb-1">
        <span className="text-[0.65rem] uppercase tracking-widest font-bold text-wine-400">{label}</span>
        <span className="text-xs font-semibold text-wine-900">{value}</span>
      </div>
      <div className="h-1.5 w-full bg-wine-100 rounded-full overflow-hidden">
        <div 
          className="h-full bg-gradient-to-r from-wine-400 to-wine-600 rounded-full transition-all duration-1000" 
          style={{ width: `${pct}%` }}
        ></div>
      </div>
    </div>
  );
};

// Helper Component: Collapsible Section
const CollapsibleSection = ({ 
  title, 
  icon: Icon, 
  children, 
  defaultOpen = false 
}: { 
  title: string; 
  icon: React.ElementType; 
  children: React.ReactNode;
  defaultOpen?: boolean;
}) => {
  const [isOpen, setIsOpen] = useState(defaultOpen);

  return (
    <div className="bg-white border border-wine-100 rounded-2xl overflow-hidden shadow-sm transition-all duration-300">
      <button 
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex items-center justify-between p-4 bg-white hover:bg-wine-50/50 transition-colors"
      >
        <div className="flex items-center gap-2">
          <div className="p-1.5 bg-wine-50 rounded-lg text-wine-600">
            <Icon className="w-4 h-4" />
          </div>
          <span className="font-serif font-bold text-wine-900">{title}</span>
        </div>
        {isOpen ? <ChevronUp className="w-4 h-4 text-wine-400" /> : <ChevronDown className="w-4 h-4 text-wine-400" />}
      </button>
      
      <div 
        className={`transition-[max-height,opacity] duration-300 ease-in-out ${isOpen ? 'max-h-[500px] opacity-100' : 'max-h-0 opacity-0'}`}
      >
        <div className="p-4 pt-0 border-t border-wine-50">
          {children}
        </div>
      </div>
    </div>
  );
};

export const WineDisplay: React.FC<WineDisplayProps> = ({ data, imagePreview }) => {
  
  const displayImage = imagePreview || data.onlineImage || 'https://images.unsplash.com/photo-1559563362-c667ba5f5480?auto=format&fit=crop&q=80&w=600';
  
  const WebsiteWrapper = ({ children }: { children: React.ReactNode }) => {
    if (data.websiteUrl) {
      return (
        <a href={data.websiteUrl} target="_blank" rel="noopener noreferrer" className="group relative block cursor-pointer">
          {children}
          <div className="absolute inset-0 bg-black/0 group-hover:bg-black/10 transition-colors flex items-center justify-center opacity-0 group-hover:opacity-100 rounded-xl">
             <div className="bg-white/90 px-3 py-1.5 rounded-full shadow-lg flex items-center gap-2 transform translate-y-2 group-hover:translate-y-0 transition-all">
                <ExternalLink className="w-3 h-3 text-wine-900" />
             </div>
          </div>
        </a>
      );
    }
    return <div className="relative">{children}</div>;
  };

  const downloadInfo = () => {
    // ... (Existing download logic, kept brief for this file update but would normally be here)
     const content = `WINE REPORT: ${data.name}\nGenerated by Sommelier AI\n\nVintage: ${data.vintage}\nDetails: ${data.varietals.join(', ')} - ${data.region}\n\nNotes:\n${data.nose}\n${data.taste}\n\nAnalysis:\nPrice: ${data.marketPrice}\nScore: ${data.criticScores?.[0]?.score || 'N/A'}`;
     const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
     const link = document.createElement('a');
     link.href = URL.createObjectURL(blob);
     link.download = `${data.name.slice(0,10)}_Report.txt`;
     link.click();
  };

  return (
    <div className="pb-20 space-y-6">
      
      {/* ZONE 1: SNAPSHOT (Header) */}
      <div className="bg-white rounded-[2.5rem] p-6 shadow-xl border border-wine-100/50 relative overflow-hidden mx-4">
        {/* Decorative BG */}
        <div className="absolute -top-10 -right-10 w-40 h-40 bg-wine-50 rounded-full blur-3xl"></div>

        <div className="relative z-10 flex gap-5">
            {/* Left: Image */}
            <div className="w-1/3 shrink-0">
               <WebsiteWrapper>
                  <div className="aspect-[3/4] rounded-2xl overflow-hidden bg-white border border-wine-50 shadow-inner relative">
                    <img 
                      src={displayImage} 
                      className="w-full h-full object-contain p-2 mix-blend-multiply" 
                      alt={data.name} 
                    />
                    {data.vintage && (
                        <div className="absolute bottom-0 inset-x-0 bg-wine-900/90 text-white text-center text-xs font-bold py-1 backdrop-blur-sm">
                            {data.vintage}
                        </div>
                    )}
                  </div>
               </WebsiteWrapper>
            </div>

            {/* Right: Info */}
            <div className="flex-1 flex flex-col justify-center">
                <div className="flex items-center gap-1.5 text-wine-600 text-xs font-bold uppercase tracking-wider mb-2">
                    <MapPin className="w-3 h-3" />
                    <span className="line-clamp-1">{data.country}</span>
                </div>
                <h2 className="text-2xl font-serif font-bold text-wine-950 leading-tight mb-3">
                    {data.name}
                </h2>
                
                {/* Region / Grape Pills */}
                <div className="flex flex-wrap gap-1.5 mb-4">
                    <span className="px-2 py-0.5 bg-wine-50 text-wine-800 text-[10px] font-bold rounded-md uppercase tracking-wide border border-wine-100">
                        {data.region}
                    </span>
                    {data.varietals.slice(0, 2).map(v => (
                         <span key={v} className="px-2 py-0.5 bg-stone-100 text-stone-600 text-[10px] font-bold rounded-md uppercase tracking-wide border border-stone-200">
                            {v}
                        </span>
                    ))}
                </div>

                {/* Price & Score Anchor */}
                <div className="flex items-center gap-3 mt-auto">
                    <div>
                        <p className="text-[10px] text-stone-400 uppercase font-bold">Market Price</p>
                        <p className="text-lg font-serif font-bold text-wine-900">{data.marketPrice}</p>
                    </div>
                    {data.criticScores && data.criticScores.length > 0 && (
                        <div className="pl-3 border-l border-wine-100">
                            <p className="text-[10px] text-stone-400 uppercase font-bold">Top Score</p>
                            <div className="flex items-center gap-1">
                                <span className="bg-gold-500 text-white text-xs font-bold px-1.5 rounded-sm">
                                    {data.criticScores[0].score}
                                </span>
                                <span className="text-[10px] font-bold text-wine-800">{data.criticScores[0].critic.split(' ')[0]}</span>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
      </div>

      {/* ZONE 2: SENSORY (The Experience) */}
      <div className="mx-4">
        <h3 className="ml-2 mb-3 text-xs font-bold text-wine-400 uppercase tracking-widest flex items-center gap-2">
            <Activity className="w-4 h-4" /> Sensory Profile
        </h3>
        
        <div className="bg-white rounded-[2rem] p-6 shadow-lg border border-wine-100/50">
            {/* Style Meters */}
            {data.styleProfile && (
                <div className="grid grid-cols-1 gap-1 mb-6">
                    <StyleMeter label="Body & Weight" value={data.styleProfile.body} />
                    <StyleMeter label="Acidity & Freshness" value={data.styleProfile.acidity} />
                    <StyleMeter label="Tannin Structure" value={data.styleProfile.tannins} />
                </div>
            )}

            {/* Flavor Tags */}
            <div className="space-y-4">
                <div>
                    <div className="flex items-center gap-2 mb-2">
                        <Droplet className="w-4 h-4 text-wine-400" />
                        <span className="text-xs font-bold text-wine-900 uppercase">Nose & Palate</span>
                    </div>
                    <div className="flex flex-wrap gap-2">
                        {[...data.nose.split(','), ...data.taste.split(',')].slice(0, 8).map((note, i) => (
                            <span key={i} className="px-3 py-1 bg-wine-50 text-wine-800 text-xs font-medium rounded-full border border-wine-100 capitalize">
                                {note.trim()}
                            </span>
                        ))}
                    </div>
                </div>
            </div>

            {/* Service Row */}
            {data.pairing && (
                <div className="mt-6 pt-6 border-t border-wine-50 grid grid-cols-3 gap-2 text-center">
                    <div className="bg-stone-50 p-3 rounded-xl">
                        <Thermometer className="w-5 h-5 text-wine-400 mx-auto mb-1" />
                        <p className="text-[10px] font-bold text-stone-400 uppercase">Temp</p>
                        <p className="text-xs font-bold text-wine-900 leading-tight mt-1">{data.pairing.temperature.replace('°C', '°')}</p>
                    </div>
                    <div className="bg-stone-50 p-3 rounded-xl">
                        <WineIcon className="w-5 h-5 text-wine-400 mx-auto mb-1" />
                        <p className="text-[10px] font-bold text-stone-400 uppercase">Glass</p>
                        <p className="text-xs font-bold text-wine-900 leading-tight mt-1">{data.pairing.glassware.split(' ')[0]}</p>
                    </div>
                    <div className="bg-stone-50 p-3 rounded-xl">
                        <Clock className="w-5 h-5 text-wine-400 mx-auto mb-1" />
                        <p className="text-[10px] font-bold text-stone-400 uppercase">Decant</p>
                        <p className="text-xs font-bold text-wine-900 leading-tight mt-1">{data.pairing.decanting.replace('minutes', 'min')}</p>
                    </div>
                </div>
            )}
        </div>
      </div>

      {/* ZONE 3: ANALYSIS (The Investment) */}
      <div className="mx-4">
         <h3 className="ml-2 mb-3 text-xs font-bold text-wine-400 uppercase tracking-widest flex items-center gap-2">
            <TrendingUp className="w-4 h-4" /> Value Analysis
        </h3>

        {data.aging && (
            <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-[2rem] p-6 text-white shadow-xl relative overflow-hidden">
                {/* Glow effect */}
                <div className="absolute top-0 right-0 w-64 h-64 bg-blue-500/10 rounded-full blur-3xl pointer-events-none"></div>

                {/* Timeline Visual */}
                <div className="relative mb-8">
                     <div className="flex justify-between text-[10px] uppercase font-bold text-slate-400 mb-2">
                        <span>Start</span>
                        <span className="text-gold-400">Peak Maturity</span>
                        <span>End</span>
                     </div>
                     <div className="h-2 bg-slate-700 rounded-full relative">
                        {/* Fake active bar for visual effect */}
                        <div className="absolute left-[10%] right-[10%] h-full bg-gradient-to-r from-slate-600 via-gold-500 to-slate-600 rounded-full opacity-80"></div>
                     </div>
                     <div className="flex justify-between text-sm font-bold mt-2 font-mono">
                        <span>{data.aging.drinkFrom}</span>
                        <span className="text-gold-400">{data.aging.peakYears}</span>
                        <span>{data.aging.drinkUntil}</span>
                     </div>
                </div>

                {/* Chart */}
                {data.vintageComparison && data.vintageComparison.length > 0 && (
                    <div className="mb-6 bg-slate-800/50 rounded-xl p-2 border border-white/5">
                        <VintageChart data={data.vintageComparison} currentVintage={data.vintage} />
                    </div>
                )}

                {/* ROI */}
                <div className="flex justify-between items-center bg-white/5 rounded-xl p-4 border border-white/10">
                    <div>
                        <p className="text-[10px] text-slate-400 uppercase font-bold">Projected 5yr Value</p>
                        <p className="text-lg font-bold text-emerald-400">{data.aging.estimatedValue5Years}</p>
                    </div>
                    <div className="text-right">
                        <p className="text-[10px] text-slate-400 uppercase font-bold">Investment Grade</p>
                        <p className="text-sm font-bold text-white">{data.aging.investmentPotential}</p>
                    </div>
                </div>
            </div>
        )}
      </div>

      {/* ZONE 4: EXPLORER (The Deep Dive - Collapsible) */}
      <div className="mx-4 space-y-3">
         
         {/* Pairing Accordion (If list is long) */}
         {data.pairing && (
            <CollapsibleSection title="Food Matches" icon={Utensils}>
                <div className="flex flex-wrap gap-2">
                    {data.pairing.foods.map((food, i) => (
                        <div key={i} className="flex items-center gap-2 bg-wine-50 px-3 py-2 rounded-lg border border-wine-100">
                             <div className="w-1.5 h-1.5 rounded-full bg-wine-400"></div>
                             <span className="text-sm text-wine-900 font-medium">{food}</span>
                        </div>
                    ))}
                </div>
            </CollapsibleSection>
         )}

         {/* Terroir Accordion */}
         {data.terroir && (
            <CollapsibleSection title="Terroir & Winemaking" icon={Mountain}>
                <div className="space-y-4">
                    {data.terroir.soil.length > 0 && (
                        <div>
                             <p className="text-[10px] font-bold text-stone-400 uppercase mb-1">Soil Composition</p>
                             <p className="text-sm text-stone-800">{data.terroir.soil.join(', ')}</p>
                        </div>
                    )}
                    {data.terroir.oak && (
                        <div>
                             <p className="text-[10px] font-bold text-stone-400 uppercase mb-1">Oak Regimen</p>
                             <p className="text-sm text-stone-800">{data.terroir.oak}</p>
                        </div>
                    )}
                    <div className="flex flex-wrap gap-2 pt-2">
                        {data.terroir.farming.map((f, i) => (
                            <span key={i} className="text-[10px] font-bold bg-green-50 text-green-700 px-2 py-1 rounded border border-green-200 uppercase">
                                {f}
                            </span>
                        ))}
                    </div>
                </div>
            </CollapsibleSection>
         )}

         {/* History Accordion */}
         <CollapsibleSection title="Winery Heritage" icon={BookOpen} defaultOpen={false}>
             <div className="space-y-4">
                 <p className="text-sm text-stone-600 leading-relaxed italic">
                    "{data.wineryInfo}"
                 </p>
                 
                 {data.bestVintages && (
                     <div className="bg-stone-50 p-3 rounded-xl border border-stone-100">
                         <p className="text-[10px] font-bold text-stone-400 uppercase mb-2">Legendary Vintages</p>
                         <div className="flex flex-wrap gap-2">
                             {data.bestVintages.map((y, i) => (
                                 <span key={i} className="text-xs font-bold text-wine-800">{y}</span>
                             ))}
                         </div>
                     </div>
                 )}

                 {data.funFacts && (
                     <div className="space-y-2">
                         {data.funFacts.map((fact, i) => (
                             <div key={i} className="flex gap-2 text-sm text-stone-600">
                                 <Lightbulb className="w-4 h-4 text-gold-500 shrink-0 mt-0.5" />
                                 <span>{fact}</span>
                             </div>
                         ))}
                     </div>
                 )}
             </div>
         </CollapsibleSection>
      </div>

      {/* Download Button */}
      <div className="px-6">
        <button 
          onClick={downloadInfo}
          className="w-full bg-white border border-wine-200 text-wine-900 py-3 rounded-xl font-bold text-sm flex items-center justify-center gap-2 active:scale-95 transition-all shadow-sm hover:bg-wine-50"
        >
          <Download className="w-4 h-4" />
          Save Report
        </button>
      </div>

    </div>
  );
};
